### ISSUE TITLE
Provide better metadata for the incidents page

### ISSUE THREAD

**Issue by AetherUnbound** [OrcaCollective/OpenOversight#113]
Currently, linking incidents in places where the page metadata is pulled leads to this:

![image](https://user-images.githubusercontent.com/10214785/149424027-de1dd2ea-b63e-4422-bf93-18cf66caba40.png)

We should provide better information here, at least so people don't see the HTML tags.

**Comment by sea-kelp** [comment]
I think this summary is being generated here:
https://github.com/OrcaCollective/OpenOversight/blob/3300e80d96ad6d122082ad1889399dc7675ca17e/OpenOversight/app/templates/incident_detail.html#L5-L9

We could use [`striptags`](https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.striptags) to remove the html from `incident.description` but I'm not sure that would be more user-friendly.

What do you think about just removing the if block from the code linked above?

**Comment by AetherUnbound** [comment]
I think it would be cool to provide _some_ context for the incident, but already the description is pretty unhelpful. So yea I think removing it would probably be easiest!
