### ISSUE TITLE
Make salary 2021 script year agnostic

### ISSUE THREAD

**Issue by AetherUnbound** [OrcaCollective/OpenOversight#135]
The salary 2021 script uses public salary information that's updated regularly. Therefore, it's not _actually_ just 2021 data but data from whenever the script itself is run. We should make the script more agnostic to which year it's being run in, and also save the raw salary data for future ingestions/tests (since that raw data is likely to change).

The script in question is here: https://github.com/OrcaCollective/OpenOversight/blob/main/data-munging/spd_2021_salary_data.py

**Comment by sea-kelp** [comment]
@AetherUnbound This line seems to be the only year-specific line in the script from what I can tell: https://github.com/OrcaCollective/OpenOversight/blob/6f913bb3416a6422a089ac7c234aacafff3a11e0/data-munging/spd_2021_salary_data.py#L58-L59

Would you mind expanding on what you mean by "save the raw salary data for future ingestions/tests"?

**Comment by AetherUnbound** [comment]
Ah, I should have linked the dataset - I meant the City Of Seattle Wage Data! https://data.seattle.gov/City-Business/City-of-Seattle-Wage-Data/2khk-5ukd

**Comment by sea-kelp** [comment]
Oh right, I meant where we're planning on saving it to - in the database or in S3?

**Comment by AetherUnbound** [comment]
Oh that's a good point! Probably S3, we can have a separate bucket for it (and use minio locally for that).

**Comment by sea-kelp** [comment]
Fixed by #324
