### ISSUE TITLE
Show featured photo in oembed data

### ISSUE THREAD

**Issue by AetherUnbound** [OrcaCollective/OpenOversight#147]
Truthfully I don't know how embeds work, but it would be rad if we could have the featured photo for an officer come up when a post is being expanded. Example:

![image](https://user-images.githubusercontent.com/10214785/175754613-6f1cae85-d2e0-49f6-8c1d-4d452a79b680.png)

**Comment by sea-kelp** [comment]
We figured out that it was a Signal glitch! For future reference, Signal uses [open graph](https://github.com/signalapp/Signal-Android/blob/c4bc2162f23e0fd6bc25941af8fb7454d91a4a35/app/src/main/java/org/thoughtcrime/securesms/linkpreview/LinkPreviewRepository.java#L160-L165) for its link previews, which we [already support](https://github.com/OrcaCollective/OpenOversight/blob/1831bd8388eaf92ea4ab178dba866cb69479529f/OpenOversight/app/templates/officer.html#L16-L29)
