### ISSUE TITLE
Add "currently on the force" filter

### ISSUE THREAD

**Issue by AetherUnbound** [OrcaCollective/OpenOversight#149]
It would be good to have a "currently on the force" checkbox on the search page.

**Comment by sea-kelp** [comment]
This might be a separate issue but it might also be helpful for the "Unit" dropdown to have an option to only search current units

**Comment by AetherUnbound** [comment]
Great point - we should have that as a separate issue!

**Comment by sea-kelp** [comment]
@AetherUnbound: Since you're more familiar with our data model, can we assume that an officer is still in a role if `retire_date` is set to null?
