### ISSUE TITLE
Create better quality thumbnails

### ISSUE THREAD

**Issue by AetherUnbound** [OrcaCollective/OpenOversight#178]
I recently tried making a tag from an existing image, and the produced image was extremely low quality even though the source image was high quality.

## Reproduction steps
1. Upload a high quality image to an officer's page
2. Click on the image
3. Click "Tag this image"
4. Add a tag that covers most of the image, select a different OO officer ID than the original
5. Observe that the new generated image is tiny (my personal example went from 8MB to 17kb)

**Comment by sea-kelp** [comment]
This is because we create a thumbnail when tagging, which makes sense to save space while focusing the officer's face, but it seems like there should be a way to pull up the original picture?
https://github.com/OrcaCollective/OpenOversight/blob/main/OpenOversight/app/utils.py#L592-L594

**Comment by AetherUnbound** [comment]
Hmm, it seems like that should only be happening if `crop_data` is not supplied 😮 

https://github.com/OrcaCollective/OpenOversight/blob/0ebb9bf60497811584ea4118ec5dca9d7f176980/OpenOversight/app/utils.py#L581-L582

The only time it's called in operational code AFAICT, it's called with the border box 🤔 

https://github.com/OrcaCollective/OpenOversight/blob/0ebb9bf60497811584ea4118ec5dca9d7f176980/OpenOversight/app/main/views.py#L1017

**Comment by sea-kelp** [comment]
Can you try reproducing the issue with the lines in my last comment commented out? The images we usually work with are hi-res so unless the crop is tiny, it's not uncommon for us to still run over the 300x300 pixel cutoff in many cases

**Comment by AetherUnbound** [comment]
After discussing this a bit more through other channels, we believe that upping the size limit from 300x300 to something like 1000x1000 would be the best approach here (along with a few other improvements mentioned in other images).
