### ISSUE TITLE
Fix "find an officer" form back button

### ISSUE THREAD

**Issue by sea-kelp** [OrcaCollective/OpenOversight#196]
https://github.com/lucyparsons/OpenOversight/issues/423

**Comment by Muhammad0776** [comment]
Hi! May I working this isseu

**Comment by AetherUnbound** [comment]
Hi there @Muhammad0776, sure! I'll assign it to you 😄 Let us know if you have any questions about getting set up or how to approach the issue - our README should have good info on the former!
