### ISSUE TITLE
Allow use of department + badge when identifying officers

### ISSUE THREAD

**Issue by AetherUnbound** [OrcaCollective/OpenOversight#200]
Presently, when using the officer identification page (e.g. `/cop_face/department/1`) one needs to use the OpenOversight officer ID in order to attach the image to an officer. Since we are already using the department in the URL, we should be able to use an officer's badge number when attaching the image. The OO Officer ID could potentially also be an option, but badge ID would be much preferred.

**Comment by sea-kelp** [comment]
@AetherUnbound: With the way we store badge numbers as assignments, is there a case where multiple officers can share the same badge number? If so, how would we want to disambiguate?

**Comment by AetherUnbound** [comment]
I think those cases are so rare that we could raise an error modal that says something along the lines of "This badge # is refers to multiple officers and is ambiguous. Please use OpenOversight ID instead". That will require that users use the current flow for badge duplicates, but that case is extremely uncommon and doesn't seem worth a large effort to try and handle. How does that sound?
