### ISSUE TITLE
Add link to original image on tag detail page

### ISSUE THREAD

**Issue by AetherUnbound** [OrcaCollective/OpenOversight#202]
We should add a link to the `original_image_id` on the Tag detail page (if the image exists and is different from `image_id`). This would be helpful for linking tagged images back to the original image.

**Comment by TomasHalgas** [comment]
Hi, could I work on this issue?

**Comment by AetherUnbound** [comment]
Hi @TomasHalgas! Gladly, I'll assign it to you 😄 Let us know if you have any questions about it!
