### ISSUE TITLE
Add isort

### ISSUE THREAD

**Issue by AetherUnbound** [OrcaCollective/OpenOversight#213]
We should add isort to the pre-commit config. Here are some potential config options we can borrow:

https://github.com/WordPress/openverse-catalog/blob/600b9eeae3fdfd8fb188f917ea45352d98d15ed1/.pre-commit-config.yaml#L27-L41

**Comment by sea-kelp** [comment]
@AetherUnbound: I think we already use isort!
https://github.com/OrcaCollective/OpenOversight/blob/main/.pre-commit-config.yaml#L33-L48

**Comment by AetherUnbound** [comment]
🤦🏼‍♀️ I do not know why my search turned up nothing within the repo. Hmm, what prompted the module moves in #205 😮

**Comment by sea-kelp** [comment]
> Hmm, what prompted the module moves in #205 open_mouth

Sorry if that was a rhetorical question but I removed the "mock" package which was a backport of the python3 unittest.mock package, so isort moved ~mock~ unittest.mock into the built-ins section of imports

**Comment by AetherUnbound** [comment]
AH! Perfect, thank you for that explanation! I see it now in the diff 😄
