### ISSUE TITLE
Add `-y` option for `bulk-add-officers` to bypass user prompt

### ISSUE THREAD

**Issue by AetherUnbound** [OrcaCollective/OpenOversight#222]
Similar to 221, it would be nice to be able to bypass the user prompt when performing the bulk upload that's part of `just fresh-start`. This is already possible if the end is set to "testing", but the CLI argument would be useful too:

https://github.com/OrcaCollective/OpenOversight/blob/c7ce36c1ad91edfe0bd2601caa6b41df41f5871f/OpenOversight/app/commands.py#L534

**Comment by sonali-rajput** [comment]
Can you please help me out how would I implement it as a cli?

**Comment by AetherUnbound** [comment]
Hi @sonali-rajput, please go ahead! I'll assign it to you 😄

**Comment by AetherUnbound** [comment]
Okay thanks for your patience @sonali-rajput - what we'll need to do is add another option to the command here which is just a boolean flag for skipping the check prompt:

https://github.com/OrcaCollective/OpenOversight/blob/c7ce36c1ad91edfe0bd2601caa6b41df41f5871f/OpenOversight/app/commands.py#L438-L452

Then in the check step mentioned in the issue description, we also add another condition for seeing if that command line argument was passed in, and skip the prompt yes/no. This would look like:

```python
if current_app.config["ENV"] == "testing" or bypass_prompt or prompt_yes_no(
    "Do you want to commit the above changes?"
):
```

You can also use the `--update-static-fields` as an example of a boolean flag parameter. Let me know if you have any more questions!
