### ISSUE TITLE
Replace usages of FLASK_ENV

### ISSUE THREAD

**Issue by sea-kelp** [OrcaCollective/OpenOversight#241]
`FLASK_ENV` and `app.env` will be removed in Flask 2.3
https://flask.palletsprojects.com/en/2.2.x/config/#ENV

```
tests/routes/test_auth.py::test_user_can_register_with_legit_credentials
tests/routes/test_auth.py::test_user_can_get_password_reset_token_sent_with_differently_cased_email
tests/routes/test_auth.py::test_user_can_get_a_confirmation_token_resent
tests/routes/test_auth.py::test_user_can_get_password_reset_token_sent
tests/routes/test_auth.py::test_user_can_get_email_reset_token_sent_with_password
tests/routes/test_auth.py::test_user_can_confirm_account_with_valid_token
tests/routes/test_user_api.py::test_register_user_approval_required
tests/routes/test_user_api.py::test_admin_can_resend_user_confirmation_email
tests/routes/test_user_api.py::test_admin_approval_sends_confirmation_email[False-False-True]
  /usr/src/app/OpenOversight/app/email.py:24: DeprecationWarning: 'app.env' is deprecated and will be removed in Flask 2.3. Use 'app.debug' instead.
    if app.env in ("staging", "production"):

```

**Comment by rsk2** [comment]
Hi @sea-kelp, I have a question regarding this issue. So per my understanding, any occurrence of  **app.env** needs to changed to **app.debug** in the code. But what about **FLASK_ENV**?

**Comment by sea-kelp** [comment]
Hi @rsk2, thanks for the question! We use `FLASK_ENV` to [differentiate](https://github.com/OrcaCollective/OpenOversight/blob/999dc9bf30f0df0cd16aae066e29f1bab150d7f7/OpenOversight/app/config.py#L88-L93) between our development, testing, and production configurations, as well as to [prevent emails from being sent](https://github.com/OrcaCollective/OpenOversight/blob/999dc9bf30f0df0cd16aae066e29f1bab150d7f7/OpenOversight/app/email.py#L24-L30) in dev/test, so I think the binary `FLASK_DEBUG` probably will not work for us.

I think the simplest thing to do here would be to just introduce a new env variable which serves the same purpose as `FLASK_ENV`. What do you think @AetherUnbound ?

**Comment by AetherUnbound** [comment]
Yea, that should work! We could just use `ENVIRONMENT` I think 🙂

**Comment by rsk2** [comment]
Ok thanks. Can I work on this?

**Comment by sea-kelp** [comment]
@rsk2 Yes, please do!
