### ISSUE TITLE
Use `multiple` with `select` rather than divs with extra CSS in filter form

### ISSUE THREAD

**Issue by AetherUnbound** [OrcaCollective/OpenOversight#94]
`select` actually has a `multiple` attribute that might be perfect for this instead of a checkbox and extra CSS: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#attr-multiple

IIRC it will render it as scrollable text box of a fixed height. Though might not be as intuitive to some folks how to select multiple (you have to control + click to select more than one... though most folks with moderate computer literacy will have learned that trick I think? Not sure)

_Originally posted by @sarayourfriend in https://github.com/OrcaCollective/OpenOversight/pull/91#r776908947_

**Comment by sea-kelp** [comment]
Fixed by #133!
